# Generated by Django 3.1.4 on 2020-12-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('poster_path', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=1000)),
                ('popularity', models.FloatField()),
            ],
        ),
    ]
